version: '3.5'
services:
  local-stack-sample:
    container_name: local-stack-sample
    image: 'localstack/localstack:0.11.2'
    restart: always
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      #- DOCKER_HOST=unix:///var/run/docker.sock
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - SERVICES=sqs
      - HOSTNAME_EXTERNAL=localhost
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'

  setup-resources:
    image: mesosphere/aws-cli
    volumes:
      - ./dev_env:/project/dev_env
    environment:
      - AWS_ACCESS_KEY_ID=AKIAEXAMPLE123
      - AWS_SECRET_ACCESS_KEY=accesskey
      - AWS_DEFAULT_REGION=us-east-1
    entrypoint: /bin/sh -c
    command: >
      "
        sleep 20
        # Executing SQS
        aws sqs create-queue --endpoint-url=http://localhost:4566 --queue-name spring-boot-amazon-sqs;
      "
    depends_on:
      - local-stack-sample
